name: SimpleSchematics
main: fr.vahor.simpleschematics.SimpleSchematics
version: '${version}'
author: Vahor
description: SimpleSchematics
depend: [FastAsyncWorldEdit]

commands:
  s:
    description: SimpleSchematics command

